brace_style = "PreferSameLine"
empty_item_single_line = false
match_block_trailing_comma = true
max_width = 80
single_line_if_else_max_width = 80
struct_lit_single_line = false
tab_spaces = 2
trailing_semicolon = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
