color="Always"
edition="2021"
use_small_heuristics="Max"
imports_granularity="Crate"
brace_style="PreferSameLine"
match_arm_leading_pipes="Preserve"
control_brace_style="AlwaysSameLine"
format_strings=true
reorder_impl_items=true
force_multiline_blocks=true
empty_item_single_line=false
struct_lit_single_line=false
overflow_delimited_expr=true
use_field_init_shorthand=true
match_block_trailing_comma=true
short_array_element_width_threshold=60
tab_spaces=2
max_width=80
wrap_comments=true
enum_discrim_align_threshold=10
struct_field_align_threshold=10
