enable_esc_key = true
clipboard_cmd = "cliphist list | tofi | cliphist decode | wl-copy"
app_launcher_cmd = "tofi-run | xargs hyprctl dispatch exec"

[modules]
left = [ [ "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "Clock", "Privacy", "Tray", "Settings" ] ]

[workspaces]
visibility_mode = "All"
enable_workspace_filling = true
workspace_names = [" ", " ", "  ", "󰎚 ", " ", "", "", " ", "󰊗 ", " "]

[appearance]
font_name = "Noto Sans"
scale_factor = 1
style = "Solid"

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
